name: 'Automatic clear dynamic&follow'
on:
  workflow_dispatch:
      branches:
      - main
  schedule:
    - cron: '0 17 1 * *'
env:
  CLEAR: ${{ secrets.CLEAR }}
  PAT: ${{ secrets.PAT }}
  SCKEY: ${{ secrets.SCKEY }}
  QQ_SKEY: ${{ secrets.QQ_SKEY}}
  QQ_MODE: ${{ secrets.QQ_MODE}}
  BARK_PUSH: ${{ secrets.BARK_PUSH }}
  BARK_SOUND: ${{ secrets.BARK_SOUND }}
  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
  TG_USER_ID: ${{ secrets.TG_USER_ID }}
  TG_PROXY_HOST: ${{ secrets.TG_PROXY_HOST }}
  TG_PROXY_PORT: ${{ secrets.TG_PROXY_PORT }}
  DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
  DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
  QYWX_KEY: ${{ secrets.QYWX_KEY}}
  IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY }}
  PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
  PUSH_PLUS_USER: ${{ secrets.PUSH_PLUS_USER }}
jobs:
  lottery_1:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'Use Node.js'
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.5'
      - name: 'Run in Nodejs'
        shell: bash
        env:
          NUMBER: 1
          COOKIE: ${{ secrets.COOKIE }}
        run: |
          npm install
          npm run clear
  lottery_2:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'Use Node.js'
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.5'
      - name: 'Run in Nodejs'
        shell: bash
        env:
          NUMBER: 2
          COOKIE: ${{ secrets.COOKIE2 }}
        run: |
          npm install
          npm run clear
  lottery_3:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'Use Node.js'
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.5'
      - name: 'Run in Nodejs'
        shell: bash
        env:
          NUMBER: 3
          COOKIE: ${{ secrets.COOKIE3 }}
        run: |
          npm install
          npm run clear
  lottery_4:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'Use Node.js'
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.5'
      - name: 'Run in Nodejs'
        shell: bash
        env:
          NUMBER: 4
          COOKIE: ${{ secrets.COOKIE4 }}
        run: |
          npm install
          npm run clear
  lottery_5:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'Use Node.js'
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.5'
      - name: 'Run in Nodejs'
        shell: bash
        env:
          NUMBER: 5
          COOKIE: ${{ secrets.COOKIE5 }}
        run: |
          npm install
          npm run clear
