name: 'Automatic sweepstakes'
on:
  push:
    branches:
      - main
    paths:
      - 'lib/**'
  workflow_dispatch:
    branches:
      - main
  schedule:
    - cron: '0 */3 * * *'
env:
  MY_CONFIG: ${{ secrets.MY_CONFIG }}
  PAT: ${{ secrets.PAT }}
  SCKEY: ${{ secrets.SCKEY }}
  QQ_SKEY: ${{ secrets.QQ_SKEY}}
  QQ_MODE: ${{ secrets.QQ_MODE}}
  BARK_PUSH: ${{ secrets.BARK_PUSH }}
  BARK_SOUND: ${{ secrets.BARK_SOUND }}
  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
  TG_USER_ID: ${{ secrets.TG_USER_ID }}
  DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
  DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
  QYWX_KEY: ${{ secrets.QYWX_KEY}}
  IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY }}
  PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
  PUSH_PLUS_USER: ${{ secrets.PUSH_PLUS_USER }}

jobs:
  lottery_1:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'Use Node.js'
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.5'
      - name: 'Run in Nodejs'
        shell: bash
        env:
          NUMBER: 1
          COOKIE: ${{ secrets.COOKIE }}
        run: |
          npm install
          npm start
      - name: 'Upload dyid to artifact'
        uses: actions/upload-artifact@v2
        with:
          name: dyid.txt
          path: lib/dyid.txt
  lottery_2:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'Use Node.js'
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.5'
      - name: 'Run in Nodejs'
        shell: bash
        env:
          NUMBER: 2
          COOKIE: ${{ secrets.COOKIE2 }}
        run: |
          npm install
          npm start
      - name: 'Upload dyid to artifact'
        uses: actions/upload-artifact@v2
        with:
          name: dyid.txt
          path: lib/dyid.txt
  lottery_3:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'Use Node.js'
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.5'
      - name: 'Run in Nodejs'
        shell: bash
        env:
          NUMBER: 3
          COOKIE: ${{ secrets.COOKIE3 }}
        run: |
          npm install
          npm start
      - name: 'Upload dyid to artifact'
        uses: actions/upload-artifact@v2
        with:
          name: dyid.txt
          path: lib/dyid.txt
  lottery_4:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'Use Node.js'
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.5'
      - name: 'Run in Nodejs'
        shell: bash
        env:
          NUMBER: 4
          COOKIE: ${{ secrets.COOKIE4 }}
        run: |
          npm install
          npm start
      - name: 'Upload dyid to artifact'
        uses: actions/upload-artifact@v2
        with:
          name: dyid.txt
          path: lib/dyid.txt
  lottery_5:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'Use Node.js'
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.5'
      - name: 'Run in Nodejs'
        shell: bash
        env:
          NUMBER: 5
          COOKIE: ${{ secrets.COOKIE5 }}
        run: |
          npm install
          npm start
      - name: 'Upload dyid to artifact'
        uses: actions/upload-artifact@v2
        with:
          name: dyid.txt
          path: lib/dyid.txt
