name: 'Automatic sweepstakes'
on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: '0 */2 * * *'
jobs:
  lottery:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'Use Node.js'
        uses: actions/setup-node@v1
        with:
          node-version: '12.18.3'
      - name: 'Run in Nodejs'
        shell: bash
        env:
          COOKIE: ${{ secrets.COOKIE }}
        run:
          node main.js COOKIE="$COOKIE"
