name: 'Automatic sweepstakes'
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - '*.md'
  workflow_dispatch:
    branches:
      - main
  schedule:
    - cron: '0 */2 * * *'
jobs:
  lottery_1:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'Use Node.js'
        uses: actions/setup-node@v1
        with:
          node-version: '12.18.3'
      - name: 'Run in Nodejs'
        shell: bash
        env:
          NUMBER: 1
          COOKIE: ${{ secrets.COOKIE }}
          SCKEY: ${{ secrets.SCKEY }}
          MY_CONFIG: ${{ secrets.MY_CONFIG }}
        run:
          npm start
  lottery_2:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'Use Node.js'
        uses: actions/setup-node@v1
        with:
          node-version: '12.18.3'
      - name: 'Run in Nodejs'
        shell: bash
        env:
          NUMBER: 2
          COOKIE: ${{ secrets.COOKIE2 }}
          SCKEY: ${{ secrets.SCKEY }}
          MY_CONFIG: ${{ secrets.MY_CONFIG }}
        run:
          npm start
  lottery_3:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'Use Node.js'
        uses: actions/setup-node@v1
        with:
          node-version: '12.18.3'
      - name: 'Run in Nodejs'
        shell: bash
        env:
          NUMBER: 3
          COOKIE: ${{ secrets.COOKIE3 }}
          SCKEY: ${{ secrets.SCKEY }}
          MY_CONFIG: ${{ secrets.MY_CONFIG }}
        run:
          npm start
  lottery_4:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'Use Node.js'
        uses: actions/setup-node@v1
        with:
          node-version: '12.18.3'
      - name: 'Run in Nodejs'
        shell: bash
        env:
          NUMBER: 4
          COOKIE: ${{ secrets.COOKIE4 }}
          SCKEY: ${{ secrets.SCKEY }}
          MY_CONFIG: ${{ secrets.MY_CONFIG }}
        run:
          npm start
  lottery_5:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'Use Node.js'
        uses: actions/setup-node@v1
        with:
          node-version: '12.18.3'
      - name: 'Run in Nodejs'
        shell: bash
        env:
          NUMBER: 5
          COOKIE: ${{ secrets.COOKIE5 }}
          SCKEY: ${{ secrets.SCKEY }}
          MY_CONFIG: ${{ secrets.MY_CONFIG }}
        run:
          npm start
